CREATE OR REPLACE VIEW playerinfo (NAME,NUMBER,DATEOFBIRTH,COUNTRY,ASSOCIATION,GROUP)
AS
SELECT p.NAME,p.NUMBER,p.DATEOFBIRTH,p.COUNTRY,t.NAME,t.GROUP
FROM PLAYERS p,TEAM t
WHERE p.COUNTRY=t.COUNTRY
;
